---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4725965189-ohGJzFZrg9ZZrp4u2Kcn3YTx19l72PEHBYX8afX
:access_token_secret: GuqNpyz15Al5oKcb3djTQQbRDUqZ3CQRqaKxZtumi6AWK
